### ISSUE TITLE
Error while building: Too many arguments for public abstract fun get(): Byte defined in java.nio.ByteBuffer

### ISSUE THREAD

**Issue by sourTaste000** [wnuke/hl-mc-kt#2] opened 2020-09-24 21:23 UTC
```
sourtaste000@pineapple-2 hl-mc-kt % ./gradlew build

> Task :compileKotlin FAILED
e: /Users/sourtaste000/hl-mc-kt/src/main/kotlin/protocol/NBT.kt: (82, 28): Too many arguments for public abstract fun get(): Byte defined in java.nio.ByteBuffer
e: /Users/sourtaste000/hl-mc-kt/src/main/kotlin/protocol/NBT.kt: (82, 31): Too many arguments for public abstract fun get(): Byte defined in java.nio.ByteBuffer

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
1 actionable task: 1 executed
sourtaste000@pineapple-2 hl-mc-kt % 
```

**Comment by sourTaste000** [comment] 2020-09-24 21:32
```
sourtaste000@pineapple-2 ~ % /usr/libexec/java_home -V
Matching Java Virtual Machines (4):
    15, x86_64: "AdoptOpenJDK 15"       /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
    11.0.8, x86_64:     "AdoptOpenJDK 11"       /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
    11.0.8, x86_64:     "Java SE 11.0.8"        /Library/Java/JavaVirtualMachines/jdk-11.0.8.jdk/Contents/Home
    1.8.0_261, x86_64:  "Java SE 8"     /Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
```

**Comment by sourTaste000** [comment] 2020-09-24 21:32
```
sourtaste000@pineapple-2 ~ % java -version
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)
sourtaste000@pineapple-2 ~ % 
```

**Comment by wnuke** [comment] 2020-09-25 06:39
Cannot reproduce on latest, closing this, reopen if it still occurs.

**Closed by wnuke** 2020-09-25 06:39 UTC
